rabbitmq:
  connection:
    addresses: localhost #port 5672 is inferred, as the AMQP default
    username: guest
    password: guest
    virtualHost: /
  consumer:
    queue: squawks_queue

server.port: 8082